In [3]:
import numpy as np
list1 = [1,2,3,4]
arr1 = np.array(list1)
print(f"arr1: {arr1}, datatype: {type(arr1)}")
ar_list = [1,2,3,4]
print(f"ar_list: {ar_list}, datatype: {type(ar_list)}")

arr1: [1 2 3 4], datatype: <class 'numpy.ndarray'>
ar_list: [1, 2, 3, 4], datatype: <class 'list'>


In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)
arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
# Print `my_array`
print(my_array)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]
[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# Using arange
arr3 = np.arange(0, 10, 2)  # start, stop, step
print("arange:", arr3)
# Using linspace
arr4 = np.linspace(0, 10, 3)  # 2 values between 0 and 10
print("linspace:", arr4)
# Using linspace
arr4 = np.linspace(0, 20, 3)  # 3 values between 0 and 20
print("linspace:", arr4)

arange: [0 2 4 6 8]
linspace: [ 0.  5. 10.]
linspace: [ 0. 10. 20.]


In [6]:
import time
start = time.time()

# for i in range(1000000):
    # i*2 

py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.28246188163757324

 Numpy operation time:  0.008267641067504883


In [7]:
current_time = time.time() 
print("Current time in seconds since epoch:", current_time)

Current time in seconds since epoch: 1774522743.7865276


In [10]:
# 1st code
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)
# 2nd code
ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("sequnce array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.92052558 0.4070819  0.66161548]
 [0.89573882 0.03139767 0.21003476]]
sequnce array: 
 [ 0  2  4  6  8 10]


In [11]:
# Identity matrix
eye = np.eye(4)
print("Identity matrix:\n", eye)

# Random values
rand = np.random.rand(2, 3)  # values in [0, 1)
print("Random:\n", rand)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random:
 [[0.57555558 0.27497709 0.30421141]
 [0.99325181 0.33627664 0.58190084]]


In [12]:
a = np.array([[1, 2, 3], [4, 5.5, 6]])
print(a)
print("Shape:", a.shape)       # (2, 3)
print("Size:", a.size)         # 6
print("Dimensions:", a.ndim)   # 2
print("Data type:", a.dtype)   # int32 or int64 depending on system

[[1.  2.  3. ]
 [4.  5.5 6. ]]
Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: float64


In [13]:
# vector = 1d
# matrix = 2d
# Tensor = nd
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2, 44], [3, 4, 55]], 
                   [[5, 6, 66], [7, 8, 88]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[ 1  2 44]
  [ 3  4 55]]

 [[ 5  6 66]
  [ 7  8 88]]]


In [14]:
arr = np.arange(12)
print("Original array ", arr, "Shape: ", arr.shape)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped, "Shape: ", reshaped.shape)

flattened = reshaped.flatten() # Convert multi-dimensional array to 1D
print("\n Flattened array ", flattened, )

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11] Shape:  (12,)

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] Shape:  (3, 4)

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [15]:
a = [[10, 20, 30], [40, 50, 60]]  # List

print(a[0][1])  # 20
print(a[1])     # [40 50 60]
print(a[:][1])  # column 1: [20 50]
print(a[0:2][1:])  # rows 0-1, cols 1-2

20
[40, 50, 60]
[40, 50, 60]
[[40, 50, 60]]


In [17]:
a = np.array([[10, 20, 30], [40, 50, 60]])

print(a[0, 1])  # 20
print(a[1])     # [40 50 60]
print(a[:, 1])  # column 1: [20 50]
print(a[0:2, 1:])  # rows 0-1, cols 1-2

20
[40 50 60]
[20 50]
[[20 30]
 [50 60]]
